**문제 1: 배열 생성 및 변형**
1부터 25까지의 숫자를 포함하는 1차원 배열을 만든 후, 이 배열을 5x5 크기의 2차원 배열로 변형하세요.


In [20]:
import numpy as np
from numpy import broadcast
from numpy.ma.core import reshape

M1 = np.arange(1,26)
print(f"원본 배열 :\n{M1}\n")

M1_1 = M1.reshape(5,5)
print(f"5 x 5 배열 : \n{M1_1}")





원본 배열 :
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]

5 x 5 배열 : 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


**문제 2: 배열 슬라이싱**
위 1번 문제에서 생성한 5x5 배열에서, 아래 그림과 같이 안쪽에 위치한 3x3 배열(값 7부터 19까지)을 슬라이싱하여 추출하세요.

In [19]:
print(f"5x5 배열 M1_1 : \n{M1_1}\n")
M2 = M1_1[1:4, 1:4]
print(f"M2 : \n{M2}")
# 첫 번째 1:4는 행을, 두 번째 1:4는 열을 지정

5x5 배열 M1_1 : 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

M2 : 
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


**문제 3: 브로드캐스팅 활용 연산**
2x3 크기의 배열 `A = np.array([[5, 10, 15], [20, 25, 30]])`가 있습니다. 이 배열의 첫 번째 행에는 100을, 두 번째 행에는 200을 더하세요. 브로드캐스팅을 활용하여 한 줄의 코드로 해결해 보세요.
(힌트: `[[100], [200]]` 형태의 배열을 더해야 합니다.)

In [23]:
A = np.array([[5, 10, 15], [20, 25, 30]])
print(f"A : \n{A}")
add = np.array([[100], [200]])
print(f"A : \n{add}")
#  넘파이는 이 배열을 다음과 같이 확장하여 A 배열의 각 행에 맞춰줍니다.
# add =
#       [[100, 100, 100],
#       [200, 200, 200]]
sum = np.add(A, add)
print(f"A : \n{sum}")


A : 
[[ 5 10 15]
 [20 25 30]]
A : 
[[100]
 [200]]
A : 
[[105 110 115]
 [220 225 230]]


**문제 4: 불리언 인덱싱 (필터링)**
0부터 15까지의 숫자를 가진 4x4 배열을 만드세요. 이 배열에서 3의 배수만 모두 추출하여 1차원 배열로 만드세요.

In [30]:
M4 = np.arange(0, 16)
print(f"M4 : \n{M4}\n")
M4_1 = M4.reshape(4, 4)
print(f"M4_1 : \n{M4_1}\n")

M4_2 = M4_1[M4_1 % 3 == 0]
# # M4_1 % 3 == 0은 3으로 나눈 나머지가 0인 요소(3의 배수)를 True로
print(f"M4_2 : \n{M4_2}\n")

M4 : 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

M4_1 : 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

M4_2 : 
[ 0  3  6  9 12 15]



**문제 5: 통계 연산 (축 기준)**
다음은 4일간 3개 상점의 일일 매출 데이터입니다.
`sales = np.array([[50, 60, 55], [80, 95, 75], [40, 100, 90], [70, 85, 80]])`
각 상점별(열 기준) 평균 매출과 각 날짜별(행 기준) 총매출을 각각 계산하세요.


In [35]:
sales = np.array([[50, 60, 55], [80, 95, 75], [40, 100, 90], [70, 85, 80]])
print(f"sales : \n{sales}\n")
M5 = np.mean(sales, axis=0)
#  axis=0은 위에서 아래'로 연산 (각 열의 요소들)
print(f"각 상점별 평균매출, M5 : \n{M5}\n")
M5_1 = np.sum(sales, axis=1)
# axis=1은 '왼쪽에서 오른쪽'으로 연산 (각 행의 요소들)
print(f"각 날짜별 총매출, M5_1 : \n{M5_1}")

sales : 
[[ 50  60  55]
 [ 80  95  75]
 [ 40 100  90]
 [ 70  85  80]]

각 상점별 평균매출, M5 : 
[60. 85. 75.]

각 날짜별 총매출, M5_1 : 
[165 250 230 235]


**문제 6: `np.where` 활용**
1부터 10까지의 숫자를 가진 배열에서, 5보다 큰 숫자는 제곱하고, 5보다 작거나 같은 숫자는 0으로 바꾸는 새로운 배열을 생성하세요.


In [42]:
M6 = np.arange(1,11)
print(f"M6 : \n{M6}\n")
M6_1 = []
M6_1 = np.where(M6 > 5, M6**2, 0)
print(f"M6_1 : \n{M6_1}")


M6 : 
[ 1  2  3  4  5  6  7  8  9 10]

M6_1 : 
[  0   0   0   0   0  36  49  64  81 100]


**문제 7: `argmax` 활용**
어떤 선수의 주간 득점 기록이 `scores = np.array([12, 25, 8, 31, 19, 22, 15])`와 같습니다. 이 선수가 가장 높은 득점을 기록한 것은 몇 번째 주(week)인지 찾아내세요. (인덱스는 0부터 시작)


In [45]:
scores = np.array([12, 25, 8, 31, 19, 22, 15])
print(f"scores : \n{scores}\n")
M7 = np.argmax(scores)
print(f"M7 : \n{M7}")

scores : 
[12 25  8 31 19 22 15]

M7 : 
3


**문제 8: 배열 합치기**
`a = np.array([[1, 2], [3, 4]])`와 `b = np.array([[5, 6]])`가 있습니다. `b`를 `a`의 아래에 수직으로 붙여서 3x2 배열을 만드세요.


In [54]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
print(f"a : \n{a}\n")
print(f"b : \n{b}\n")
c = np.vstack([b, a])
print(f"c : \n{c}")

a : 
[[1 2]
 [3 4]]

b : 
[[5 6]]

c : 
[[5 6]
 [1 2]
 [3 4]]


**문제 9: 결측치(NaN) 처리**
다음 배열에서 결측치(`np.nan`)의 개수를 세고, 결측치를 해당 배열의 전체 평균값(결측치를 제외한)으로 대체하세요.
`data = np.array([10., 20., np.nan, 30., 40., np.nan, 50.])`

In [63]:
data = np.array([10., 20., np.nan, 30., 40., np.nan, 50.])
print(f"data : \n{data}\n")
# 일반적인 sum 함수는 nan을 반환
print(f"일반 sum() 결과: {np.sum(data)}\n")

# nan을 제외하고 합계 계산
print(f"nansum() 결과: {np.nansum(data)}\n")

# nan이 어디에 있는지 확인
print(f"결측치 위치 확인 (isnan):\n{np.isnan(data)}")

data : 
[10. 20. nan 30. 40. nan 50.]

일반 sum() 결과: nan

nansum() 결과: 150.0

결측치 위치 확인 (isnan):
[False False  True False False  True False]


**문제 10: 종합 응용**
10x2 크기의 배열에 0부터 99까지의 정수를 무작위로 채우세요. 이 배열은 (x, y) 좌표 목록으로 간주합니다. 이 중에서 x값(0번 열)이 y값(1번 열)보다 큰 모든 좌표(행)를 찾아 출력하세요.

In [78]:
M10 = np.random.randint(low=0, high=100, size=(10,2))
print(f"M10 : \n{M10}\n")
M10_1 = M10[M10[:, 0] > M10[:, 1]]
print(f"M10_1 : \n{M10_1}\n")


M10 : 
[[34  4]
 [75 26]
 [81  0]
 [73 18]
 [89  0]
 [52 37]
 [60  7]
 [64 98]
 [53 85]
 [35 48]]

M10_1 : 
[[34  4]
 [75 26]
 [81  0]
 [73 18]
 [89  0]
 [52 37]
 [60  7]]

